name: flutter-app

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: linux
            artifact: linux-amd64
          - runner: windows-latest
            target: windows
            artifact: windows-amd64
          - runner: macos-13
            target: macos
            artifact: macos-amd64
          - runner: macos-latest
            target: macos
            artifact: macos-arm64
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install build tools
        if: ${{ matrix.platform.target == 'linux' }}
        run: sudo apt update && sudo apt install -y curl git unzip xz-utils zip libglu1-mesa clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Set up Rinf
        run: cargo install rinf
      - name: Generate message
        run: rinf message
        working-directory: bulletin-board-gui
      - name: Build flutter app
        run: flutter build ${{ matrix.platform.target }}
        working-directory: bulletin-board-gui
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.artifact }}
          path: bulletin-board-gui/build/${{ matrix.platform.target }}